### ISSUE TITLE
 cannot import name 'idle' from 'pytgcalls

### ISSUE THREAD

**Issue by bsde1234** [TG-Musics/TG-VC-Bot#20]
python3.9 main.py
Traceback (most recent call last):
  File "/var/www/html/VcPlayer/main.py", line 2, in <module>
    from pytgcalls import idle
ImportError: cannot import name 'idle' from 'pytgcalls' (/home/admin/.local/lib/python3.9/site-packages/pytgcalls/__init__.py

**Comment by vi2k6** [comment]
Changed py-tgcalls version
