### ISSUE TITLE
MusicBot

### ISSUE THREAD

**Issue by alyvnahid** [TG-Musics/TG-VC-Bot#9]

**Comment by alyvnahid** [comment]
Salam

**Comment by shivaprasadreddy4** [comment]
[cryptogrammusicbot-logs-1631338774766.txt](https://github.com/TG-Musics/Telegram_Vc_Bot/files/7147309/cryptogrammusicbot-logs-1631338774766.txt)


Could you please check these logs and help me fix the issue? Appreciate if you can make a step by step guide to creating a VC music bot.
